import styles from "./Home.module.scss";
import Page from "@modules/Page/Page";
import PageHeader from "@modules/PageHeader/PageHeader";

export default function Home() {
  return (
    <Page>
      <PageHeader title="Home" />
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
      <p>I am home page!</p>
    </Page>
  );
}
